server:
  port: 8763
spring:
  application:
    name: supplier-commodity
##����ע��
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
##��������
zuul:
  routes:
    supplier-order:
      path: /supplier/order/**
      serviceId: supplier-order
    supplier-commodity:
      path: /supplier/commodity/**
      serviceId: supplier-commodity
    supplier-user:
      path: /supplier/commodity/**
      serviceId: supplier-commodity